import { useEffect, useState } from "react";
import { Contract, JsonRpcProvider } from "ethers";
import { Link } from "react-router-dom";
import { NFT_FACTORY_ADDRESS, nftFactoryAbi, isNFTLaunchpadConfigured } from "@/lib/nftLaunch/launchpad";
import type { NFTProject } from "@/lib/nftLaunch/types";

export default function NFTLaunches() {
  const [items, setItems] = useState<NFTProject[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!isNFTLaunchpadConfigured) return; let active = true; (async () => { try { const provider = new JsonRpcProvider(String(import.meta.env.VITE_NFT_RPC_URL || "https://bsc-dataseed.binance.org/"), 56); const factory = new Contract(NFT_FACTORY_ADDRESS, nftFactoryAbi, provider); const count = Number(await factory.allCollectionsLength()); const next: NFTProject[] = []; for (let i = count - 1; i >= Math.max(0, count - 24); i -= 1) { const address = String(await factory.allCollections(i)); const project = await factory.projects(address); next.push({ collection: address, creator: String(project.creator), name: "NFT Collection", symbol: "NFT", description: String(project.description), imageURI: String(project.imageURI), baseURI: "", metadataURI: String(project.metadataURI), maxSupply: "", mintPrice: "", maxMintPerWallet: "", createdAt: Number(project.createdAt) }); } if (active) setItems(next); } catch (e) { if (active) setError(e instanceof Error ? e.message : String(e)); } })(); return () => { active = false; }; }, []);
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-end justify-between"><div><p className="text-sm text-[#9CA3AF]">NFT Factory 项目</p><h1 className="text-3xl font-bold text-white">已发行 NFT 合集</h1></div><Link to="/nft-launch" className="rounded-xl bg-[#D0FF00] px-4 py-2 text-sm font-semibold text-black">创建合集</Link></div>{!isNFTLaunchpadConfigured && <div className="rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-200">NFT Factory 尚未部署或未配置。</div>}{error && <div className="rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <article key={item.collection} className="overflow-hidden rounded-2xl border border-[#25282C] bg-[#111215]"><div className="aspect-square bg-[#0A0B0D]">{item.imageURI && <img src={item.imageURI} className="h-full w-full object-cover"/>}</div><div className="p-4"><h2 className="font-semibold text-white">{item.name}</h2><p className="mt-2 line-clamp-2 text-sm text-[#9CA3AF]">{item.description || "暂无描述"}</p><a className="mt-3 block break-all text-xs text-[#D0FF00]" href={`https://bscscan.com/address/${item.collection}`} target="_blank" rel="noreferrer">{item.collection}</a></div></article>)}</div>{!error && !items.length && isNFTLaunchpadConfigured && <p className="text-sm text-[#6B7280]">暂无已发行合集。</p>}</div>;
}
