import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Contract } from "ethers";
import { NFT_FACTORY_ADDRESS, nftFactoryAbi, isNFTLaunchpadConfigured, loadNFTProject, nftProvider } from "@/lib/nftLaunch/launchpad";
import type { NFTProject } from "@/lib/nftLaunch/types";

export default function NFTLaunches() {
  const [items, setItems] = useState<NFTProject[]>([]); const [error, setError] = useState("");
  useEffect(() => { if (!isNFTLaunchpadConfigured) return; let active = true; (async () => { try { const factory = new Contract(NFT_FACTORY_ADDRESS, nftFactoryAbi, nftProvider); const count = Number(await factory.allCollectionsLength()); const addresses = await Promise.all(Array.from({ length: Math.min(24, count) }, (_, offset) => factory.allCollections(count - 1 - offset))); const next = await Promise.all(addresses.map((address) => loadNFTProject(String(address)))); if (active) setItems(next); } catch (e) { if (active) setError(e instanceof Error ? e.message : String(e)); } })(); return () => { active = false; }; }, []);
  return <div className="mx-auto max-w-6xl space-y-6"><div className="flex items-end justify-between"><div><p className="text-sm text-[#9CA3AF]">NFT Factory 项目</p><h1 className="text-3xl font-bold text-white">已发行 NFT 合集</h1></div><Link to="/nft-launch" className="rounded-xl bg-[#D0FF00] px-4 py-2 text-sm font-semibold text-black">创建合集</Link></div>{!isNFTLaunchpadConfigured && <div className="rounded-xl border border-amber-400/30 bg-amber-400/10 p-4 text-sm text-amber-200">NFT Factory 尚未部署或未配置。</div>}{error && <div className="rounded-xl border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</div>}<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <Link to={`/nft/${item.collection}`} key={item.collection} className="group overflow-hidden rounded-2xl border border-[#25282C] bg-[#111215] transition hover:border-[#D0FF00]/40"><div className="aspect-square bg-[#0A0B0D]">{item.imageURI && <img src={item.imageURI} alt={item.name} className="h-full w-full object-cover transition group-hover:scale-[1.02]"/>}</div><div className="p-4"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-white">{item.name}</h2><span className="text-xs text-[#D0FF00]">{item.mintPrice} BNB</span></div><p className="mt-2 line-clamp-2 text-sm text-[#9CA3AF]">{item.description || "暂无描述"}</p><div className="mt-3 flex items-center justify-between text-xs text-[#6B7280]"><span>{item.totalMinted}/{item.maxSupply} 已铸造</span><span>查看并铸造 →</span></div></div></Link>)}</div>{!error && !items.length && isNFTLaunchpadConfigured && <p className="text-sm text-[#6B7280]">暂无已发行合集。</p>}</div>;
}
