import { useState } from "react";
import { Image as ImageIcon, Loader2, Rocket } from "lucide-react";
import { useWallet } from "@/hooks/useWallet";
import { useAppStore } from "@/store";
import { generateImage, sendChatMessage, DEFAULT_MODEL } from "@/lib/kimi";
import { createNFTLaunch, isNFTLaunchpadConfigured, NFT_CREATION_FEE, queueNFTVerification, uploadNFTAsset } from "@/lib/nftLaunch/launchpad";
import { formatEther } from "ethers";

export default function NFTLaunch() {
  const wallet = useWallet(); const { showToast } = useAppStore();
  const [form, setForm] = useState({ name: "", symbol: "", description: "", imageURI: "", baseURI: "https://api.kimi-vault.com/nft/", metadataURI: "", maxSupply: "1000", mintPrice: "0.01", maxMintPerWallet: "10", prompt: "" });
  const [busy, setBusy] = useState(""); const [result, setResult] = useState("");
  const update = (key: string, value: string) => setForm((prev) => ({ ...prev, [key]: value }));
  const generate = async () => { setBusy("image"); try { const dataUrl = await generateImage({ prompt: form.prompt || `NFT collection artwork for ${form.name || "Kimi"}, square, clean, premium` }); update("imageURI", await uploadNFTAsset(dataUrl)); showToast({type:"success",message:"NFT 图片生成并上传成功"}); } catch(e) { showToast({type:"error",message:e instanceof Error?e.message:"生图失败"}); } finally { setBusy(""); } };
  const describe = async () => { setBusy("text"); try { const text = await sendChatMessage({ model: DEFAULT_MODEL, messages: [{role:"user",content:`为 NFT 合集 ${form.name} 写一段 80 字以内中文介绍，主题：${form.prompt}`}], stream:false }); update("description", text.trim()); } catch(e) { showToast({type:"error",message:e instanceof Error?e.message:"文案生成失败"}); } finally { setBusy(""); } };
  const deploy = async () => { if (!wallet.isConnected || !wallet.signer) { await wallet.connectWallet(); return; } if (!wallet.isBSC) { await wallet.switchToBSC(); return; } setBusy("deploy"); try { const res = await createNFTLaunch(wallet.signer, form); setResult(res.collection); if (res.collection) void queueNFTVerification(res.collection); showToast({type:"success",message:"NFT 合集创建成功，源码验证已提交"}); } catch(e) { showToast({type:"error",message:e instanceof Error?e.message:"创建失败"}); } finally { setBusy(""); } };
  const fields = [["name","合集名称"],["symbol","Symbol"],["description","合集描述"],["prompt","图片主题/提示词"],["maxSupply","总供应量"],["mintPrice","单枚铸造价 BNB"],["maxMintPerWallet","单钱包上限"],["baseURI","Token 元数据 Base URI"],["metadataURI","合集元数据 URI"]];
  return <div className="mx-auto max-w-5xl space-y-6"><div><p className="text-sm text-[#9CA3AF]">NFT Deployer + Factory</p><h1 className="text-3xl font-bold text-white">创建 NFT 合集</h1><p className="mt-2 text-sm text-[#9CA3AF]">工厂手续费 {formatEther(NFT_CREATION_FEE)} BNB + Gas。AI 生图沿用钱包签名、余额门槛和限流保护。</p></div><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border border-[#25282C] bg-[#111215] p-5 space-y-4">{fields.map(([key,label]) => <label key={key} className="block"><span className="mb-1 block text-xs text-[#9CA3AF]">{label}</span>{key === "description" || key === "prompt" ? <textarea value={form[key as keyof typeof form]} onChange={e=>update(key,e.target.value)} rows={3} className="w-full rounded-xl border border-[#25282C] bg-[#0A0B0D] p-3 text-sm text-white"/> : <input value={form[key as keyof typeof form]} onChange={e=>update(key,e.target.value)} className="w-full rounded-xl border border-[#25282C] bg-[#0A0B0D] p-3 text-sm text-white"/>}</label>)}<div className="flex flex-wrap gap-3"><button onClick={generate} disabled={!!busy} className="rounded-xl border border-[#D0FF00]/40 px-4 py-2 text-sm text-[#D0FF00]">{busy === "image" ? <Loader2 className="inline h-4 w-4 animate-spin"/> : <ImageIcon className="inline h-4 w-4"/>} 生成图片</button><button onClick={describe} disabled={!!busy} className="rounded-xl border border-[#25282C] px-4 py-2 text-sm text-white">生成描述</button><button onClick={deploy} disabled={!!busy || !isNFTLaunchpadConfigured} className="rounded-xl bg-[#D0FF00] px-5 py-2 text-sm font-semibold text-black"><Rocket className="mr-1 inline h-4 w-4"/>一键创建</button></div>{!isNFTLaunchpadConfigured && <p className="text-xs text-amber-300">NFT Factory 地址尚未配置；合约编译后部署 Factory，并设置 VITE_NFT_FACTORY_ADDRESS 才能提交链上交易。</p>}{result && <p className="break-all rounded-xl bg-[#D0FF00]/10 p-3 text-sm text-[#D0FF00]">合集地址：{result}</p>}</div><div className="rounded-2xl border border-[#25282C] bg-[#111215] p-5">{form.imageURI ? <img src={form.imageURI} className="aspect-square w-full rounded-2xl object-cover"/> : <div className="flex aspect-square items-center justify-center rounded-2xl bg-[#0A0B0D] text-sm text-[#6B7280]">生成的 NFT 图片预览</div>}<p className="mt-4 text-xs leading-5 text-[#6B7280]">图片生成结果需要上传为公开资产 URI，才能被钱包和市场读取。当前支持已有后端资产接口接入。</p></div></div></div>;
}
